# .github/workflows/frontend-deploy.yml
# Author: Refiloe Radebe
# Date: 2025-02-06
# Description: GitHub Actions workflow to deploy the React frontend to Vercel.

name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install
        working-directory: ./meal-planner-frontend/

      - name: Build Project
        run: npm run build
        working-directory: ./meal-planner-frontend/

      - name: Deploy to Vercel
        uses: Vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./meal-planner-frontend/
          vercel-args: "--prod"
