# .github/workflows/frontend-deploy.yml
# Author: Refiloe Radebe
# Date: 2025-02-06
# Description: GitHub Actions workflow to deploy the React frontend to Render.

name: Deploy Frontend to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./meal-planner-frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./meal-planner-frontend

      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
